import {html, LitElement, TemplateResult} from 'lit';
import {customElement, property, query, state} from 'lit/decorators.js';
import {when} from 'lit/directives/when.js';
import {Task} from '@lit/task';
import {PurchaseContextType} from '../model/purchase-context.ts';
import {EmailMessage} from '../model/email-message.ts';
import {PageAndContent} from '../model/reservation.ts';
import {EventService} from '../service/event.ts';
import {EmailLogService} from '../service/email-log.ts';
import {readRouteParams, replaceRouteParams, toPageNumber} from '../service/helpers.ts';
import {localizedTitle} from '../service/reservation-format.ts';
import {base, modernLayout, purchaseContextListPage, retroCompat, textColors} from '../styles.ts';
import {AlfioPageChange} from '../components/pagination-bar.ts';
import {ListSearchController} from '../components/list-search.ts';
import {taskContent} from '../components/task-content.ts';
import {EmailTable} from './email-table.ts';
import '../components/pagination-bar.ts';
import './email-table.ts';

interface EmailLogData {
    title: string;
    timeZone: string;
    messages: PageAndContent<EmailMessage[]>;
}

const ITEMS_PER_PAGE = 50;

/**
 * E-mails generated by an event or a subscription.
 * When "data-message-id" is set, the given message is displayed as soon as the list has been loaded.
 */
@customElement('alfio-email-log')
export class EmailLog extends LitElement {
    @property({ type: String, attribute: 'data-purchase-context-type' }) purchaseContextType: PurchaseContextType = 'event';
    @property({ type: String, attribute: 'data-public-identifier' }) publicIdentifier = '';
    // subscriptions only: events are loaded to retrieve their title and time zone
    @property({ type: String, attribute: 'data-title' }) purchaseContextTitle = '';
    @property({ type: String, attribute: 'data-time-zone' }) timeZone = '';
    @property({ type: Number, attribute: 'data-message-id' }) messageId?: number;
    @state() private search = '';
    @state() private page = 1;
    @state() private lastData: EmailLogData | null = null;
    @query('alfio-email-table') private emailTable!: EmailTable;

    private readonly searchController = new ListSearchController(this, (search) => {
        this.search = search;
        this.page = 1;
        this.syncLocation();
    });

    private readonly loadDataTask = new Task(this, {
        task: async ([type, publicIdentifier, search, page]): Promise<EmailLogData> => {
            const [context, messages] = await Promise.all([
                this.loadPurchaseContext(type, publicIdentifier),
                EmailLogService.list(type, publicIdentifier, page, search),
            ]);
            return { ...context, messages };
        },
        args: () => [this.purchaseContextType, this.publicIdentifier, this.search, this.page] as const,
        // Task invokes this only for the latest request. Keep results mounted during refreshes.
        onComplete: (data) => {
            const firstLoad = this.lastData == null;
            this.lastData = data;
            // NaN while AngularJS hasn't interpolated the attribute yet
            if (firstLoad && this.messageId != null && this.messageId > 0) {
                this.updateComplete.then(() => this.emailTable.openMessage(this.messageId!));
            }
        },
    });

    static readonly styles = [
        base,
        retroCompat,
        textColors,
        modernLayout,
        purchaseContextListPage,
    ];

    connectedCallback(): void {
        super.connectedCallback();
        const params = readRouteParams();
        this.search = params.get('search') ?? '';
        this.searchController.init(this.search);
        this.page = toPageNumber(params.get('page'));
    }

    render(): TemplateResult {
        return taskContent(this.loadDataTask, this.lastData, 'Failed to load e-mails. Please try again.',
            (data) => this.renderContent(data));
    }

    private renderContent(data: EmailLogData): TemplateResult {
        const messages = data.messages;
        return html`
            <div class="container">
                <div class="page-title-row secondary">
                    <h1>E-mail Log for <i>${data.title}</i></h1>
                </div>
                <p class="page-description text-muted">All the e-mails generated by the current ${this.purchaseContextType}.</p>
                <hr class="page-separator" />
                <div class="filter-toolbar">
                    <div class="filter-left">${this.searchController.render('e-mails')}</div>
                </div>
                ${when(messages.right === 0,
                    () => html`<section class="section-card">${this.renderTable(data)}</section>`,
                    () => html`
                        ${this.renderTable(data)}
                        <alfio-pagination-bar
                            .page=${this.page}
                            .total=${messages.right}
                            page-size=${ITEMS_PER_PAGE}
                            item-label="e-mails"
                            @alfio-page-change=${this.onPageChange}
                        ></alfio-pagination-bar>
                    `)}
            </div>
        `;
    }

    private renderTable(data: EmailLogData): TemplateResult {
        return html`
            <alfio-email-table
                .messages=${data.messages.left}
                data-purchase-context-type=${this.purchaseContextType}
                data-public-identifier=${this.publicIdentifier}
                data-time-zone=${data.timeZone}
            ></alfio-email-table>
        `;
    }

    private async loadPurchaseContext(type: PurchaseContextType, publicIdentifier: string): Promise<{ title: string, timeZone: string }> {
        if (type === 'event') {
            const { event } = await EventService.load(publicIdentifier);
            return { title: localizedTitle(event), timeZone: event.timeZone };
        }
        return { title: this.purchaseContextTitle || publicIdentifier, timeZone: this.timeZone || 'UTC' };
    }

    private onPageChange = (event: AlfioPageChange): void => {
        this.page = event.detail.page;
        this.syncLocation();
    };

    private syncLocation(): void {
        replaceRouteParams(new URLSearchParams({ page: String(this.page), search: this.search }));
    }
}

declare global {
    interface HTMLElementTagNameMap {
        'alfio-email-log': EmailLog;
    }
}
