services:
  alfio:
    image: alfio/alf.io
    depends_on:
        db:
            condition: service_healthy
    env_file:
         - .env
    ports:
      - "8080:8080"
    profiles:
        - prod
  db:
    image: postgres:10
    env_file:
        - .env
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U alfio -d alfio" ]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - data-volume:/var/lib/postgresql/data
    profiles:
        - dev
        - prod
volumes:
  data-volume:
