volumes:
    data-volume:

services:
    db:
        image: postgres:10
        env_file:
            - .env
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        ports:
            - target: 5432
              published: 5432
              protocol: tcp
              mode: host
        volumes:
            - data-volume:/var/lib/postgresql/data
###########################################################################
# If you want to try out Alf.io, you can uncomment the following service: #
###########################################################################
#    alfio:
#        image: alfio/alf.io
#        env_file:
#            - .env
#        depends_on:
#            db:
#                condition: service_healthy
#        ports:
#            - "8080:8080"
