/**
 * This file is part of alf.io.
 *
 * alf.io is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * alf.io is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with alf.io.  If not, see <http://www.gnu.org/licenses/>.
 */
package alfio.repository;

import alfio.model.BillingDocument;
import ch.digitalfondue.npjt.*;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Optional;

@QueryRepository
public interface BillingDocumentRepository {

    @Query("select * from billing_document where reservation_id_fk = :reservationId order by generation_ts desc limit 1")
    Optional<BillingDocument> findLatestByReservationId(@Bind("reservationId") String reservationId);

    @Query("insert into billing_document(event_id_fk, number, reservation_id_fk, type, model, generation_ts, status)" +
        " values(:eventId, :number, :reservationId, :type, :model, :generationTimestamp, 'VALID')")
    @AutoGeneratedKey("id")
    AffectedRowCountAndKey<Integer> insert(@Bind("eventId") int eventId, @Bind("reservationId") String reservationId, @Bind("number") String number,
                                           @Bind("type") BillingDocument.Type type, @Bind("model") String modelJson, @Bind("generationTimestamp")ZonedDateTime generationTs);

    @Query("select * from billing_document a inner join " +
        "(select max(generation_ts) as time,reservation_id_fk from billing_document where status = 'VALID' and type = :type and event_id_fk = :eventId group by reservation_id_fk) b" +
        " on a.generation_ts = b.time and a.reservation_id_fk = b.reservation_id_fk")
    List<BillingDocument> findAllOfTypeForEvent(@Bind("type") BillingDocument.Type type, @Bind("eventId") int eventId);

    @Query("delete from billing_document where reservation_id_fk = :reservationId and event_id_fk = :eventId")
    int deleteForReservation(@Bind("reservationId") String reservationId, @Bind("eventId") int eventId);

    @Query("delete from billing_document where reservation_id_fk in (:reservationIds) and event_id_fk = :eventId")
    int deleteForReservations(@Bind("reservationIds") List<String> reservationIds, @Bind("eventId") int eventId);
}
