package io.bagarino.datamapper;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marker annotation for retrieval of the latest auto-generated key.
 * All the method annotated with @AutoGeneratedKey <b>must</b> return a {@code Pair<Integer, keyClass>}
 */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface AutoGeneratedKey {
    String value() default "";
    Class<?> keyClass() default Integer.class;
}
