package io.bagarino.controller;

public interface ErrorsCode {

	String STEP_1_SELECT_AT_LEAST_ONE = "error.STEP_1_SELECT_AT_LEAST_ONE";
	String STEP_1_OVER_MAXIMUM = "error.STEP_1_OVER_MAXIMUM";
	String STEP_1_TICKET_CATEGORY_MUST_BE_SALEABLE = "error.STEP_1_TICKET_CATEGORY_MUST_BE_SALEABLE";
	String STEP_1_ACCESS_RESTRICTED = "error.STEP_1_ACCESS_RESTRICTED";
	String STEP_1_NOT_ENOUGH_TICKETS = "error.STEP_1_NOT_ENOUGH_TICKETS";
}
