allowBuilds:
  '@fortawesome/fontawesome-common-types': true
  '@fortawesome/fontawesome-svg-core': true
  '@fortawesome/free-brands-svg-icons': true
  '@fortawesome/free-regular-svg-icons': true
  '@fortawesome/free-solid-svg-icons': true
  esbuild: true
  nice-napi: true
