<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="/resources/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/resources/bower_components/components-font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/resources/css/application.css">
</head>
<body>


<div class="container">
<div class="row">
<div class="col-md-8 col-md-offset-2">


	The reservation with id {{reservationId}} does not exist. 

	Go back to <a href="../">event</a>
	
	
</div>
</div>
</div>

</body>
</html>