name: "E2E Test"
on:
    schedule:
        - cron:  '0 4 * * *'
    workflow_dispatch:

jobs:
    build:
        if: github.repository == 'alfio-event/alf.io'
        strategy:
            matrix:
                browser: ['chrome', 'firefox', 'safari']
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - name: Set up JDK
              uses: actions/setup-java@v6
              with:
                  java-version: 25
                  distribution: temurin
                  cache: gradle
            - name: 'BrowserStack Env Setup'
              uses: 'browserstack/github-actions/setup-env@master'
              with:
                  username: ${{ secrets.BROWSERSTACK_USERNAME }}
                  access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
            - name: Build with Gradle
              run: ./gradlew test --tests NormalFlowE2ETest -Pverbose
              env:
                  E2E_SERVER_URL: ${{ secrets.E2E_SERVER_URL }}
                  E2E_ADMIN_USERNAME: ${{ secrets.E2E_ADMIN_USERNAME }}
                  E2E_ADMIN_PASSWORD: ${{ secrets.E2E_ADMIN_PASSWORD }}
                  E2E_ORGANIZATION: ${{ secrets.E2E_ORGANIZATION }}
                  E2E_BROWSER: ${{matrix.browser}}
                  E2E_CI_RUN: true
                  ALFIO_RUN_E2E: true