name: upload-test
on:
    schedule:
        - cron:  '55 23 * * *'
jobs:
    build:
        if: github.repository == 'alfio-event/alf.io'
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:10
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: alfio
                ports:
                    - 5432:5432
                # needed because the postgres container does not provide a healthcheck
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v1
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
                  restore-keys: |
                      ${{ runner.os }}-gradlew-
            - name: install-s3cmd
              run: sudo pip install s3cmd
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Build with Gradle
              run: ./gradlew build -Dspring.profiles.active=travis -Ddbenv=PGSQL-TRAVIS
            - name: Upload artifact
              run: s3cmd put $S3_OPTIONS build/libs/alfio-*-boot.war $ARTIFACT_URI
              env:
                  S3_OPTIONS: ${{ secrets.S3_OPTIONS }}
                  ARTIFACT_URI: ${{ secrets.S3_ARTIFACT_URI }}
